name: Hardel Videography
favicon: null
layout_spectrum: 0.4172816255595535
typography_spectrum: 0.7220447768922895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7822153659071773
  lightness: 0.5484682198148221
  saturation: 0.2626606647390872
  rhythmicContrast: 0.5479068704880774
purpose: []
