title: Hardel Videography
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4591837
  brandStrength: 0.625
  lightness: 0.7030075
  brandColors:
    - '#141414'
    - '#504040'
    - '#937a68'
    - '#fefefe'
    - '#f7a86f'
  rhythmicContrast: 0.4763695
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-54230823-1
  facebook: null
favicon: null
name: Hardel Videography
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.93539
layout_spectrum: 0.462406
