name: Hardel Videography
favicon: null
layout_spectrum: 0.50511
typography_spectrum: 0.93539
title: Hardel Videography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54230823-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#504040'
    - '#937a68'
    - '#fefefe'
    - '#f7a86f'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
