name: Hardel Videography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59102
title: Hardel Videography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54230823-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#504040'
    - '#937a68'
    - '#fefefe'
    - '#f7a86f'
  brandStrength: 0.8125
  lightness: 0.5484682198148221
  saturation: 0.3125
  rhythmicContrast: 0.5479068704880774
purpose: []
