name: Hardel Videography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.93539
title: Hardel Videography
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54230823-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#504040'
    - '#937a68'
    - '#fefefe'
    - '#f7a86f'
  brandStrength: 0.625
  lightness: 0.7030075
  saturation: 0.4591837
  rhythmicContrast: 0.4763695
purpose: []
